# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'Google/SignIn'
target 'google_login' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for google_login

  target 'google_loginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'google_loginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
